# Generated by Django 2.1rc1 on 2018-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='if_fvrt',
            field=models.BooleanField(default=False),
        ),
    ]
